server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # React Router 경로에서 새로고침해도
    # index.html을 반환하도록 처리
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 해시가 붙은 Vite 정적 리소스 캐싱
    location /assets/ {
        try_files $uri =404;

        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}